## Task 1 — Clean the Data
In this step, we initialize the dataset, impute missing values for 'age' (median) and 'city' (mode), and remove any duplicate records.

In [1]:
import pandas as pd
import numpy as np

# Create dataset
df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

print("Original Data:")
display(df)

# 1. Impute missing values
df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])

# 2. Remove duplicate rows
df = df.drop_duplicates()

print("\nCleaned Data:")
display(df)

Original Data:

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

Cleaned Data:

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

## Task 2 — Encode Categorical Columns
We use One-Hot Encoding for the 'city' column to avoid ordinal bias and Label Encoding for 'gender'.

In [2]:
from sklearn.preprocessing import LabelEncoder

# One-Hot Encoding for city
df_encoded = pd.get_dummies(df, columns=['city'])

# Label Encoding for gender
le = LabelEncoder()
df_encoded['gender'] = le.fit_transform(df_encoded['gender'])

print("Encoded Data:")
display(df_encoded.head())

Encoded Data:

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
5            5  40.0       1          95000        True        False

## Task 3 — Scale Numerical Features
We demonstrate two common scaling techniques: Min-Max Scaling (normalization) and Standardization.

In [3]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Columns to scale
num_cols = ['age', 'annual_income']

# ---- Min-Max Scaling ----
minmax_scaler = MinMaxScaler()
df_minmax = df_encoded.copy()
df_minmax[num_cols] = minmax_scaler.fit_transform(df_minmax[num_cols])

print("Min-Max Scaled Data:")
display(df_minmax.head())

# ---- Standardization ----
std_scaler = StandardScaler()
df_standard = df_encoded.copy()
df_standard[num_cols] = std_scaler.fit_transform(df_standard[num_cols])

print("\nStandardized Data:")
display(df_standard.head())

Min-Max Scaled Data:

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.666667       0         0.5000        True        False
2            3  0.666667       0         0.2500        True        False
3            4  0.666667       1         1.0000       False         True
5            5  1.000000       1         0.6875        True        False

Standardized Data:

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970       False         True
1            2  0.204124       0       0.036179        True        False
2            3  0.204124       0      -0.687396        True        False
3            4  0.204124       1       1.483328       False         True
5            5  1.224745       1       0.578860        True        False

## 🧠 Explanation of Scaling Techniques

👉 **Min-Max Scaling**
* Scales values between **0 and 1**.
* Best when data has **no extreme outliers** and you need bounded values (e.g., neural networks).

👉 **Standardization**
* Transforms data to **mean = 0, std = 1**.
* Preferred when data has **outliers** or when using models like Logistic Regression or SVM.